### ISSUE TITLE
No issue per say, just wanted to say nice job

### ISSUE THREAD

**Issue by DeltaWho1** [devleaks/followthegreens#1]
Had a little play around with this and it's pretty cool. I myself wanted to get FTG directly integrated into my scenery. Perhaps something I should re-consider in future :)

**Comment by devleaks** [comment]
I wish Laminar did it in its "ATC" + taxi guidance system, in place of the yellow arrows.
If you want it directly in your scenery, pay attention to the network of taxiway. FTG relies on it. The more precise it is, the nicer FTG will be. I have some commercial sceneries, where they extend the network up to the ramp. Very nice. Other sceneries just dump a taxiway segment across an apron with any refinement. It shows in FTG.
P.

**Comment by DeltaWho1** [comment]
Yh so in my scenery, that ATC network is only on active taxiways themselves, ATC routes don't go directly onto the stand (following Laminar's and Traffic Global guidance). I see what you mean though, tested it at Gateway LMML and pathing was notably off from indicated centreline markings. Still impressed at how your system coped.
