### ISSUE TITLE
For development need to use xppython3 3.1.2 or lower!!!

### ISSUE THREAD

**Issue by Gunduran** [devleaks/followthegreens#3]
Only as a comment: 
I've updated recently to use xppython3 for 3.10 and to the version 3.1.3 (and then 3.1.4).
Unfortunately the reload-behaviour of xppython3 has changed and the author (Peter Bruckner) is trying to help and find out the cause.

The situation is: up to 3.1.2. the reload really created new bytrcode and all changes also in sub-modules (like ui.py or aircraft.py were reloaded and correct interpreted.
Starting with 3.1.3 the reload only refresh's the main PI_FollowTheGreen.py module but not the sub-modules imported afterwards. Their bytecode remains unchanged. 

Example: I've done some changes in followthegreen.py causing an typo and a traceback was shwoing the correct line.  After removing the new lines which caused the issue, I reloaded and started the tool again. It still dumped and created a traceback. But the line where the issue was has gone and it is shown the new line (same line number) that is now at this position....

I'll try to develop the next day a small test package for testing purposes of the reload functions.

Further information: In version 3.1.3 the standard logging was not producing any output to XPPython3Log.txt.

**Comment by devleaks** [comment]
OK. Thanks. Sounds difficult to track. Good luck and thank you. P.

**Comment by Gunduran** [comment]
Many thanks Pierre and have a Happy New Year.
